#!/bin/bash
# Philip Roberts Jul 25, 2021

# Bash Aliases
alias e='exit'
alias c='clear'
alias l='ls -la'
alias b="vim ~/.bashrc"
alias i="vim ~/.config/i3/config"
alias gs="git status"
alias py='python3'
alias extract="tar -xvf"

# PS1
# user@host <current dir> >
export PS1="\u@\H \W > \[$(tput sgr0)\]"
